/* krill academy — data catalog */

const GRADE_POINTS = {
  "A+": 4.0, "A": 4.0, "A-": 3.7,
  "B+": 3.3, "B": 3.0, "B-": 2.7,
  "C+": 2.3, "C": 2.0, "C-": 1.7,
  "D+": 1.3, "D": 1.0, "D-": 0.7,
  "F": 0.0
};

const FORMULAS = {
  algebra: [
    { name: "quadratic formula", formula: "x = (-b \u00b1 \u221a(b\u00b2 - 4ac)) / 2a" },
    { name: "slope", formula: "m = (y\u2082 - y\u2081) / (x\u2082 - x\u2081)" },
    { name: "slope-intercept form", formula: "y = mx + b" },
    { name: "point-slope form", formula: "y - y\u2081 = m(x - x\u2081)" },
    { name: "standard form of a line", formula: "Ax + By = C" },
    { name: "distance formula", formula: "d = \u221a((x\u2082 - x\u2081)\u00b2 + (y\u2082 - y\u2081)\u00b2)" },
    { name: "midpoint formula", formula: "M = ((x\u2081 + x\u2082)/2, (y\u2081 + y\u2082)/2)" },
    { name: "difference of squares", formula: "a\u00b2 - b\u00b2 = (a + b)(a - b)" },
    { name: "perfect square trinomial", formula: "(a + b)\u00b2 = a\u00b2 + 2ab + b\u00b2" },
    { name: "simple interest", formula: "I = Prt" },
    { name: "compound interest", formula: "A = P(1 + r/n)^(nt)" },
    { name: "logarithm change of base", formula: "log_a(b) = log(b) / log(a)" },
    { name: "absolute value equation", formula: "|x| = a \u2192 x = a or x = -a" },
    { name: "exponent product rule", formula: "a^m \u00b7 a^n = a^(m + n)" },
    { name: "exponent power rule", formula: "(a^m)^n = a^(mn)" }
  ],
  geometry: [
    { name: "area of circle", formula: "A = \u03c0r\u00b2" },
    { name: "circumference of circle", formula: "C = 2\u03c0r" },
    { name: "area of triangle", formula: "A = \u00bdbh" },
    { name: "pythagorean theorem", formula: "a\u00b2 + b\u00b2 = c\u00b2" },
    { name: "area of rectangle", formula: "A = lw" },
    { name: "perimeter of rectangle", formula: "P = 2l + 2w" },
    { name: "area of trapezoid", formula: "A = \u00bd(b\u2081 + b\u2082)h" },
    { name: "area of parallelogram", formula: "A = bh" },
    { name: "volume of sphere", formula: "V = (4/3)\u03c0r\u00b3" },
    { name: "surface area of sphere", formula: "SA = 4\u03c0r\u00b2" },
    { name: "volume of cylinder", formula: "V = \u03c0r\u00b2h" },
    { name: "volume of cone", formula: "V = (1/3)\u03c0r\u00b2h" },
    { name: "volume of rectangular prism", formula: "V = lwh" },
    { name: "arc length", formula: "s = r\u03b8" },
    { name: "area of sector", formula: "A = \u00bdr\u00b2\u03b8" }
  ],
  trigonometry: [
    { name: "sine", formula: "sin(\u03b8) = opposite / hypotenuse" },
    { name: "cosine", formula: "cos(\u03b8) = adjacent / hypotenuse" },
    { name: "tangent", formula: "tan(\u03b8) = opposite / adjacent" },
    { name: "cosecant", formula: "csc(\u03b8) = 1 / sin(\u03b8)" },
    { name: "secant", formula: "sec(\u03b8) = 1 / cos(\u03b8)" },
    { name: "cotangent", formula: "cot(\u03b8) = 1 / tan(\u03b8)" },
    { name: "pythagorean identity", formula: "sin\u00b2(\u03b8) + cos\u00b2(\u03b8) = 1" },
    { name: "law of sines", formula: "a/sin(A) = b/sin(B) = c/sin(C)" },
    { name: "law of cosines", formula: "c\u00b2 = a\u00b2 + b\u00b2 - 2ab\u00b7cos(C)" },
    { name: "double angle sine", formula: "sin(2\u03b8) = 2sin(\u03b8)cos(\u03b8)" },
    { name: "double angle cosine", formula: "cos(2\u03b8) = cos\u00b2(\u03b8) - sin\u00b2(\u03b8)" },
    { name: "half angle sine", formula: "sin(\u03b8/2) = \u00b1\u221a((1 - cos(\u03b8)) / 2)" },
    { name: "half angle cosine", formula: "cos(\u03b8/2) = \u00b1\u221a((1 + cos(\u03b8)) / 2)" },
    { name: "area of triangle (trig)", formula: "A = \u00bdab\u00b7sin(C)" },
    { name: "sum of angles sine", formula: "sin(A + B) = sin(A)cos(B) + cos(A)sin(B)" }
  ],
  calculus: [
    { name: "limit definition of derivative", formula: "f'(x) = lim(h\u21920) [f(x+h) - f(x)] / h" },
    { name: "power rule", formula: "d/dx [x^n] = nx^(n-1)" },
    { name: "product rule", formula: "d/dx [fg] = f'g + fg'" },
    { name: "quotient rule", formula: "d/dx [f/g] = (f'g - fg') / g\u00b2" },
    { name: "chain rule", formula: "d/dx [f(g(x))] = f'(g(x)) \u00b7 g'(x)" },
    { name: "derivative of sin(x)", formula: "d/dx [sin(x)] = cos(x)" },
    { name: "derivative of cos(x)", formula: "d/dx [cos(x)] = -sin(x)" },
    { name: "derivative of e^x", formula: "d/dx [e^x] = e^x" },
    { name: "derivative of ln(x)", formula: "d/dx [ln(x)] = 1/x" },
    { name: "integration power rule", formula: "\u222bx^n dx = x^(n+1)/(n+1) + C" },
    { name: "fundamental theorem of calculus", formula: "\u222b_a^b f(x)dx = F(b) - F(a)" },
    { name: "integration by parts", formula: "\u222bu dv = uv - \u222bv du" },
    { name: "l'hopital's rule", formula: "lim f(x)/g(x) = lim f'(x)/g'(x) when 0/0 or \u221e/\u221e" },
    { name: "derivative of tan(x)", formula: "d/dx [tan(x)] = sec\u00b2(x)" },
    { name: "mean value theorem", formula: "f'(c) = (f(b) - f(a)) / (b - a) for some c in (a, b)" }
  ],
  physics: [
    { name: "newton's second law", formula: "F = ma" },
    { name: "weight", formula: "W = mg" },
    { name: "kinetic energy", formula: "KE = \u00bdmv\u00b2" },
    { name: "potential energy", formula: "PE = mgh" },
    { name: "work", formula: "W = Fd\u00b7cos(\u03b8)" },
    { name: "power", formula: "P = W/t" },
    { name: "ohm's law", formula: "V = IR" },
    { name: "velocity", formula: "v = d/t" },
    { name: "acceleration", formula: "a = \u0394v/\u0394t" },
    { name: "momentum", formula: "p = mv" },
    { name: "impulse", formula: "J = F\u0394t = \u0394p" },
    { name: "density", formula: "\u03c1 = m/V" },
    { name: "pressure", formula: "P = F/A" },
    { name: "wave speed", formula: "v = f\u03bb" },
    { name: "coulomb's law", formula: "F = kq\u2081q\u2082/r\u00b2" },
    { name: "universal gravitation", formula: "F = Gm\u2081m\u2082/r\u00b2" }
  ],
  chemistry: [
    { name: "ideal gas law", formula: "PV = nRT" },
    { name: "boyle's law", formula: "P\u2081V\u2081 = P\u2082V\u2082" },
    { name: "charles's law", formula: "V\u2081/T\u2081 = V\u2082/T\u2082" },
    { name: "combined gas law", formula: "P\u2081V\u2081/T\u2081 = P\u2082V\u2082/T\u2082" },
    { name: "avogadro's law", formula: "V\u2081/n\u2081 = V\u2082/n\u2082" },
    { name: "molarity", formula: "M = moles of solute / liters of solution" },
    { name: "dilution equation", formula: "M\u2081V\u2081 = M\u2082V\u2082" },
    { name: "pH", formula: "pH = -log[H\u207a]" },
    { name: "pOH", formula: "pOH = -log[OH\u207b]" },
    { name: "pH + pOH relation", formula: "pH + pOH = 14" },
    { name: "percent composition", formula: "% = (mass of element / molar mass) \u00d7 100" },
    { name: "gibbs free energy", formula: "\u0394G = \u0394H - T\u0394S" },
    { name: "rate law", formula: "rate = k[A]^m[B]^n" },
    { name: "equilibrium constant", formula: "K = [products]^coeff / [reactants]^coeff" },
    { name: "henderson-hasselbalch", formula: "pH = pKa + log([A\u207b]/[HA])" }
  ],
  statistics: [
    { name: "mean", formula: "\u03bc = \u03a3x / n" },
    { name: "median", formula: "middle value when data is ordered" },
    { name: "mode", formula: "most frequently occurring value" },
    { name: "range", formula: "range = max - min" },
    { name: "variance", formula: "\u03c3\u00b2 = \u03a3(x - \u03bc)\u00b2 / n" },
    { name: "standard deviation", formula: "\u03c3 = \u221a(\u03a3(x - \u03bc)\u00b2 / n)" },
    { name: "z-score", formula: "z = (x - \u03bc) / \u03c3" },
    { name: "permutations", formula: "P(n,r) = n! / (n-r)!" },
    { name: "combinations", formula: "C(n,r) = n! / (r!(n-r)!)" },
    { name: "basic probability", formula: "P(A) = favorable outcomes / total outcomes" },
    { name: "addition rule", formula: "P(A or B) = P(A) + P(B) - P(A and B)" },
    { name: "multiplication rule", formula: "P(A and B) = P(A) \u00d7 P(B|A)" },
    { name: "bayes' theorem", formula: "P(A|B) = P(B|A)\u00b7P(A) / P(B)" },
    { name: "expected value", formula: "E(X) = \u03a3x\u2081P(x\u2081)" },
    { name: "binomial probability", formula: "P(X=k) = C(n,k) p^k (1-p)^(n-k)" }
  ]
};

const PERIODIC_TABLE = [
  { number: 1, symbol: "H", name: "hydrogen", mass: 1.008, category: "nonmetal" },
  { number: 2, symbol: "He", name: "helium", mass: 4.003, category: "noble gas" },
  { number: 3, symbol: "Li", name: "lithium", mass: 6.941, category: "alkali metal" },
  { number: 4, symbol: "Be", name: "beryllium", mass: 9.012, category: "alkaline earth metal" },
  { number: 5, symbol: "B", name: "boron", mass: 10.81, category: "metalloid" },
  { number: 6, symbol: "C", name: "carbon", mass: 12.011, category: "nonmetal" },
  { number: 7, symbol: "N", name: "nitrogen", mass: 14.007, category: "nonmetal" },
  { number: 8, symbol: "O", name: "oxygen", mass: 15.999, category: "nonmetal" },
  { number: 9, symbol: "F", name: "fluorine", mass: 18.998, category: "halogen" },
  { number: 10, symbol: "Ne", name: "neon", mass: 20.180, category: "noble gas" },
  { number: 11, symbol: "Na", name: "sodium", mass: 22.990, category: "alkali metal" },
  { number: 12, symbol: "Mg", name: "magnesium", mass: 24.305, category: "alkaline earth metal" },
  { number: 13, symbol: "Al", name: "aluminum", mass: 26.982, category: "post-transition metal" },
  { number: 14, symbol: "Si", name: "silicon", mass: 28.086, category: "metalloid" },
  { number: 15, symbol: "P", name: "phosphorus", mass: 30.974, category: "nonmetal" },
  { number: 16, symbol: "S", name: "sulfur", mass: 32.06, category: "nonmetal" },
  { number: 17, symbol: "Cl", name: "chlorine", mass: 35.45, category: "halogen" },
  { number: 18, symbol: "Ar", name: "argon", mass: 39.948, category: "noble gas" },
  { number: 19, symbol: "K", name: "potassium", mass: 39.098, category: "alkali metal" },
  { number: 20, symbol: "Ca", name: "calcium", mass: 40.078, category: "alkaline earth metal" },
  { number: 21, symbol: "Sc", name: "scandium", mass: 44.956, category: "transition metal" },
  { number: 22, symbol: "Ti", name: "titanium", mass: 47.867, category: "transition metal" },
  { number: 23, symbol: "V", name: "vanadium", mass: 50.942, category: "transition metal" },
  { number: 24, symbol: "Cr", name: "chromium", mass: 51.996, category: "transition metal" },
  { number: 25, symbol: "Mn", name: "manganese", mass: 54.938, category: "transition metal" },
  { number: 26, symbol: "Fe", name: "iron", mass: 55.845, category: "transition metal" },
  { number: 27, symbol: "Co", name: "cobalt", mass: 58.933, category: "transition metal" },
  { number: 28, symbol: "Ni", name: "nickel", mass: 58.693, category: "transition metal" },
  { number: 29, symbol: "Cu", name: "copper", mass: 63.546, category: "transition metal" },
  { number: 30, symbol: "Zn", name: "zinc", mass: 65.38, category: "transition metal" },
  { number: 31, symbol: "Ga", name: "gallium", mass: 69.723, category: "post-transition metal" },
  { number: 32, symbol: "Ge", name: "germanium", mass: 72.630, category: "metalloid" },
  { number: 33, symbol: "As", name: "arsenic", mass: 74.922, category: "metalloid" },
  { number: 34, symbol: "Se", name: "selenium", mass: 78.971, category: "nonmetal" },
  { number: 35, symbol: "Br", name: "bromine", mass: 79.904, category: "halogen" },
  { number: 36, symbol: "Kr", name: "krypton", mass: 83.798, category: "noble gas" },
  { number: 37, symbol: "Rb", name: "rubidium", mass: 85.468, category: "alkali metal" },
  { number: 38, symbol: "Sr", name: "strontium", mass: 87.62, category: "alkaline earth metal" },
  { number: 39, symbol: "Y", name: "yttrium", mass: 88.906, category: "transition metal" },
  { number: 40, symbol: "Zr", name: "zirconium", mass: 91.224, category: "transition metal" },
  { number: 41, symbol: "Nb", name: "niobium", mass: 92.906, category: "transition metal" },
  { number: 42, symbol: "Mo", name: "molybdenum", mass: 95.95, category: "transition metal" },
  { number: 43, symbol: "Tc", name: "technetium", mass: 98, category: "transition metal" },
  { number: 44, symbol: "Ru", name: "ruthenium", mass: 101.07, category: "transition metal" },
  { number: 45, symbol: "Rh", name: "rhodium", mass: 102.906, category: "transition metal" },
  { number: 46, symbol: "Pd", name: "palladium", mass: 106.42, category: "transition metal" },
  { number: 47, symbol: "Ag", name: "silver", mass: 107.868, category: "transition metal" },
  { number: 48, symbol: "Cd", name: "cadmium", mass: 112.414, category: "transition metal" },
  { number: 49, symbol: "In", name: "indium", mass: 114.818, category: "post-transition metal" },
  { number: 50, symbol: "Sn", name: "tin", mass: 118.710, category: "post-transition metal" },
  { number: 51, symbol: "Sb", name: "antimony", mass: 121.760, category: "metalloid" },
  { number: 52, symbol: "Te", name: "tellurium", mass: 127.60, category: "metalloid" },
  { number: 53, symbol: "I", name: "iodine", mass: 126.904, category: "halogen" },
  { number: 54, symbol: "Xe", name: "xenon", mass: 131.293, category: "noble gas" },
  { number: 55, symbol: "Cs", name: "cesium", mass: 132.905, category: "alkali metal" },
  { number: 56, symbol: "Ba", name: "barium", mass: 137.327, category: "alkaline earth metal" },
  { number: 57, symbol: "La", name: "lanthanum", mass: 138.905, category: "lanthanide" },
  { number: 58, symbol: "Ce", name: "cerium", mass: 140.116, category: "lanthanide" },
  { number: 59, symbol: "Pr", name: "praseodymium", mass: 140.908, category: "lanthanide" },
  { number: 60, symbol: "Nd", name: "neodymium", mass: 144.242, category: "lanthanide" },
  { number: 61, symbol: "Pm", name: "promethium", mass: 145, category: "lanthanide" },
  { number: 62, symbol: "Sm", name: "samarium", mass: 150.36, category: "lanthanide" },
  { number: 63, symbol: "Eu", name: "europium", mass: 151.964, category: "lanthanide" },
  { number: 64, symbol: "Gd", name: "gadolinium", mass: 157.25, category: "lanthanide" },
  { number: 65, symbol: "Tb", name: "terbium", mass: 158.925, category: "lanthanide" },
  { number: 66, symbol: "Dy", name: "dysprosium", mass: 162.500, category: "lanthanide" },
  { number: 67, symbol: "Ho", name: "holmium", mass: 164.930, category: "lanthanide" },
  { number: 68, symbol: "Er", name: "erbium", mass: 167.259, category: "lanthanide" },
  { number: 69, symbol: "Tm", name: "thulium", mass: 168.934, category: "lanthanide" },
  { number: 70, symbol: "Yb", name: "ytterbium", mass: 173.045, category: "lanthanide" },
  { number: 71, symbol: "Lu", name: "lutetium", mass: 174.967, category: "lanthanide" },
  { number: 72, symbol: "Hf", name: "hafnium", mass: 178.49, category: "transition metal" },
  { number: 73, symbol: "Ta", name: "tantalum", mass: 180.948, category: "transition metal" },
  { number: 74, symbol: "W", name: "tungsten", mass: 183.84, category: "transition metal" },
  { number: 75, symbol: "Re", name: "rhenium", mass: 186.207, category: "transition metal" },
  { number: 76, symbol: "Os", name: "osmium", mass: 190.23, category: "transition metal" },
  { number: 77, symbol: "Ir", name: "iridium", mass: 192.217, category: "transition metal" },
  { number: 78, symbol: "Pt", name: "platinum", mass: 195.084, category: "transition metal" },
  { number: 79, symbol: "Au", name: "gold", mass: 196.967, category: "transition metal" },
  { number: 80, symbol: "Hg", name: "mercury", mass: 200.592, category: "transition metal" },
  { number: 81, symbol: "Tl", name: "thallium", mass: 204.38, category: "post-transition metal" },
  { number: 82, symbol: "Pb", name: "lead", mass: 207.2, category: "post-transition metal" },
  { number: 83, symbol: "Bi", name: "bismuth", mass: 208.980, category: "post-transition metal" },
  { number: 84, symbol: "Po", name: "polonium", mass: 209, category: "post-transition metal" },
  { number: 85, symbol: "At", name: "astatine", mass: 210, category: "halogen" },
  { number: 86, symbol: "Rn", name: "radon", mass: 222, category: "noble gas" },
  { number: 87, symbol: "Fr", name: "francium", mass: 223, category: "alkali metal" },
  { number: 88, symbol: "Ra", name: "radium", mass: 226, category: "alkaline earth metal" },
  { number: 89, symbol: "Ac", name: "actinium", mass: 227, category: "actinide" },
  { number: 90, symbol: "Th", name: "thorium", mass: 232.038, category: "actinide" },
  { number: 91, symbol: "Pa", name: "protactinium", mass: 231.036, category: "actinide" },
  { number: 92, symbol: "U", name: "uranium", mass: 238.029, category: "actinide" },
  { number: 93, symbol: "Np", name: "neptunium", mass: 237, category: "actinide" },
  { number: 94, symbol: "Pu", name: "plutonium", mass: 244, category: "actinide" },
  { number: 95, symbol: "Am", name: "americium", mass: 243, category: "actinide" },
  { number: 96, symbol: "Cm", name: "curium", mass: 247, category: "actinide" },
  { number: 97, symbol: "Bk", name: "berkelium", mass: 247, category: "actinide" },
  { number: 98, symbol: "Cf", name: "californium", mass: 251, category: "actinide" },
  { number: 99, symbol: "Es", name: "einsteinium", mass: 252, category: "actinide" },
  { number: 100, symbol: "Fm", name: "fermium", mass: 257, category: "actinide" },
  { number: 101, symbol: "Md", name: "mendelevium", mass: 258, category: "actinide" },
  { number: 102, symbol: "No", name: "nobelium", mass: 259, category: "actinide" },
  { number: 103, symbol: "Lr", name: "lawrencium", mass: 266, category: "actinide" },
  { number: 104, symbol: "Rf", name: "rutherfordium", mass: 267, category: "transition metal" },
  { number: 105, symbol: "Db", name: "dubnium", mass: 268, category: "transition metal" },
  { number: 106, symbol: "Sg", name: "seaborgium", mass: 271, category: "transition metal" },
  { number: 107, symbol: "Bh", name: "bohrium", mass: 270, category: "transition metal" },
  { number: 108, symbol: "Hs", name: "hassium", mass: 277, category: "transition metal" },
  { number: 109, symbol: "Mt", name: "meitnerium", mass: 278, category: "transition metal" },
  { number: 110, symbol: "Ds", name: "darmstadtium", mass: 281, category: "transition metal" },
  { number: 111, symbol: "Rg", name: "roentgenium", mass: 282, category: "transition metal" },
  { number: 112, symbol: "Cn", name: "copernicium", mass: 285, category: "transition metal" },
  { number: 113, symbol: "Nh", name: "nihonium", mass: 286, category: "post-transition metal" },
  { number: 114, symbol: "Fl", name: "flerovium", mass: 289, category: "post-transition metal" },
  { number: 115, symbol: "Mc", name: "moscovium", mass: 290, category: "post-transition metal" },
  { number: 116, symbol: "Lv", name: "livermorium", mass: 293, category: "post-transition metal" },
  { number: 117, symbol: "Ts", name: "tennessine", mass: 294, category: "halogen" },
  { number: 118, symbol: "Og", name: "oganesson", mass: 294, category: "noble gas" }
];

const CONSTANTS = [
  { name: "pi", symbol: "\u03c0", value: "3.14159265358979..." },
  { name: "euler's number", symbol: "e", value: "2.71828182845904..." },
  { name: "speed of light", symbol: "c", value: "2.998 \u00d7 10\u2078 m/s" },
  { name: "gravitational constant", symbol: "G", value: "6.674 \u00d7 10\u207b\u00b9\u00b9 N\u00b7m\u00b2/kg\u00b2" },
  { name: "planck's constant", symbol: "h", value: "6.626 \u00d7 10\u207b\u00b3\u2074 J\u00b7s" },
  { name: "boltzmann constant", symbol: "k", value: "1.381 \u00d7 10\u207b\u00b2\u00b3 J/K" },
  { name: "avogadro's number", symbol: "N\u2090", value: "6.022 \u00d7 10\u00b2\u00b3 mol\u207b\u00b9" },
  { name: "gas constant", symbol: "R", value: "8.314 J/(mol\u00b7K)" },
  { name: "electron mass", symbol: "m\u2091", value: "9.109 \u00d7 10\u207b\u00b3\u00b9 kg" },
  { name: "proton mass", symbol: "m\u209a", value: "1.673 \u00d7 10\u207b\u00b2\u2077 kg" },
  { name: "elementary charge", symbol: "e", value: "1.602 \u00d7 10\u207b\u00b9\u2079 C" },
  { name: "faraday constant", symbol: "F", value: "96,485 C/mol" },
  { name: "vacuum permittivity", symbol: "\u03b5\u2080", value: "8.854 \u00d7 10\u207b\u00b9\u00b2 F/m" },
  { name: "golden ratio", symbol: "\u03c6", value: "1.61803398874989..." },
  { name: "vacuum permeability", symbol: "\u03bc\u2080", value: "1.257 \u00d7 10\u207b\u2076 H/m" },
  { name: "neutron mass", symbol: "m\u2099", value: "1.675 \u00d7 10\u207b\u00b2\u2077 kg" },
  { name: "coulomb's constant", symbol: "k\u2091", value: "8.988 \u00d7 10\u2079 N\u00b7m\u00b2/C\u00b2" },
  { name: "stefan-boltzmann constant", symbol: "\u03c3", value: "5.670 \u00d7 10\u207b\u2078 W/(m\u00b2\u00b7K\u2074)" },
  { name: "rydberg constant", symbol: "R\u221e", value: "1.097 \u00d7 10\u2077 m\u207b\u00b9" },
  { name: "standard gravity", symbol: "g", value: "9.80665 m/s\u00b2" },
  { name: "atomic mass unit", symbol: "u", value: "1.661 \u00d7 10\u207b\u00b2\u2077 kg" },
  { name: "planck length", symbol: "l\u209a", value: "1.616 \u00d7 10\u207b\u00b3\u2075 m" },
  { name: "standard atmosphere", symbol: "atm", value: "101,325 Pa" },
  { name: "molar volume (stp)", symbol: "V\u2098", value: "22.414 L/mol" },
  { name: "speed of sound in air", symbol: "v\u209b", value: "343 m/s (at 20\u00b0C)" },
  { name: "hubble constant", symbol: "H\u2080", value: "\u224870 km/s/Mpc" },
  { name: "water density at 4\u00b0C", symbol: "\u03c1_h2o", value: "1000 kg/m\u00b3" }
];

const GRAMMAR_RULES = {
  "parts of speech": [
    { name: "noun", desc: "a person, place, thing, or idea (e.g. dog, city, happiness)" },
    { name: "pronoun", desc: "replaces a noun to avoid repetition (e.g. he, she, it, they, we)" },
    { name: "verb", desc: "expresses an action or state of being (e.g. run, think, is, become)" },
    { name: "adjective", desc: "describes or modifies a noun (e.g. tall, blue, interesting)" },
    { name: "adverb", desc: "modifies a verb, adjective, or other adverb (e.g. quickly, very, never)" },
    { name: "preposition", desc: "shows relationship between a noun and another word (e.g. in, on, at, between)" },
    { name: "conjunction", desc: "connects words, phrases, or clauses (e.g. and, but, or, because)" },
    { name: "interjection", desc: "expresses emotion or surprise (e.g. wow, ouch, hey, oh)" },
    { name: "article", desc: "specifies a noun as definite or indefinite (a, an, the)" },
    { name: "determiner", desc: "introduces a noun and provides context (e.g. this, that, every, some)" }
  ],
  "punctuation": [
    { name: "period", desc: "ends a declarative or imperative sentence; used in abbreviations" },
    { name: "comma", desc: "separates list items; follows introductory phrases; joins independent clauses before conjunctions" },
    { name: "semicolon", desc: "joins two related independent clauses without a conjunction; separates complex list items" },
    { name: "colon", desc: "introduces a list, explanation, or quotation after an independent clause" },
    { name: "dash", desc: "sets off parenthetical information with emphasis; em dash for interruptions, en dash for ranges" },
    { name: "apostrophe", desc: "shows possession (dog's bone); indicates omitted letters in contractions (don't)" },
    { name: "quotation marks", desc: "enclose direct speech or quotations; titles of short works like articles and poems" },
    { name: "question mark", desc: "ends a direct question; not used after indirect questions" },
    { name: "exclamation point", desc: "ends an exclamatory sentence; shows strong emotion; use sparingly in formal writing" },
    { name: "parentheses", desc: "enclose supplementary or explanatory material that could be removed without changing meaning" },
    { name: "ellipsis", desc: "indicates omitted words in a quotation or a trailing off of thought (...)" },
    { name: "brackets", desc: "enclose editorial comments or clarifications inserted into quoted material" }
  ],
  "common mistakes": [
    { name: "their / there / they're", desc: "their = possession; there = location; they're = they are" },
    { name: "your / you're", desc: "your = possession (your book); you're = you are (you're welcome)" },
    { name: "its / it's", desc: "its = possession (its color); it's = it is or it has (it's raining)" },
    { name: "affect / effect", desc: "affect = verb (weather affects mood); effect = noun (the effect was immediate)" },
    { name: "then / than", desc: "then = time or sequence (then we left); than = comparison (taller than)" },
    { name: "to / too / two", desc: "to = preposition; too = also or excessive; two = number" },
    { name: "who / whom", desc: "who = subject (who called?); whom = object (to whom did you speak?)" },
    { name: "fewer / less", desc: "fewer = countable items (fewer apples); less = uncountable (less water)" },
    { name: "lie / lay", desc: "lie = recline, no object (lie down); lay = place, needs object (lay the book down)" },
    { name: "accept / except", desc: "accept = receive (accept the award); except = exclude (everyone except him)" },
    { name: "loose / lose", desc: "loose = not tight (loose shirt); lose = to misplace or fail (lose the game)" },
    { name: "complement / compliment", desc: "complement = complete something; compliment = praise someone" }
  ],
  "sentence types": [
    { name: "declarative", desc: "makes a statement or expresses an opinion (the sky is blue.)" },
    { name: "interrogative", desc: "asks a question (is the sky blue?)" },
    { name: "imperative", desc: "gives a command or makes a request (close the door.)" },
    { name: "exclamatory", desc: "expresses strong emotion or surprise (what a beautiful day!)" },
    { name: "simple sentence", desc: "contains one independent clause with a subject and predicate" },
    { name: "compound sentence", desc: "two independent clauses joined by a conjunction or semicolon" },
    { name: "complex sentence", desc: "one independent clause and at least one dependent clause" },
    { name: "compound-complex sentence", desc: "at least two independent clauses and one or more dependent clauses" }
  ]
};

const HISTORY_TIMELINES = [
  {
    name: "ancient civilizations",
    dates: "3500 BCE - 500 BCE",
    events: [
      { year: "3500 BCE", event: "earliest writing systems develop in mesopotamia (cuneiform)" },
      { year: "3100 BCE", event: "unification of upper and lower egypt under narmer" },
      { year: "2560 BCE", event: "great pyramid of giza constructed" },
      { year: "2500 BCE", event: "indus valley civilization flourishes at mohenjo-daro and harappa" },
      { year: "1754 BCE", event: "code of hammurabi established in babylon" },
      { year: "1500 BCE", event: "shang dynasty begins in china; oracle bones used for divination" },
      { year: "1200 BCE", event: "bronze age collapse across the eastern mediterranean" },
      { year: "1000 BCE", event: "kingdom of israel established under king david" },
      { year: "776 BCE", event: "first olympic games held in ancient greece" },
      { year: "753 BCE", event: "traditional founding date of rome" },
      { year: "600 BCE", event: "rise of persian empire under cyrus the great" },
      { year: "509 BCE", event: "roman republic established" }
    ]
  },
  {
    name: "classical era",
    dates: "500 BCE - 500 CE",
    events: [
      { year: "500 BCE", event: "golden age of athens begins; height of greek philosophy" },
      { year: "490 BCE", event: "battle of marathon; greeks repel persian invasion" },
      { year: "483 BCE", event: "death of siddhartha gautama (buddha)" },
      { year: "336 BCE", event: "alexander the great begins his conquests" },
      { year: "264 BCE", event: "first punic war between rome and carthage" },
      { year: "221 BCE", event: "qin dynasty unifies china; great wall construction begins" },
      { year: "44 BCE", event: "assassination of julius caesar" },
      { year: "27 BCE", event: "roman empire established under augustus" },
      { year: "4 BCE", event: "approximate birth of jesus of nazareth" },
      { year: "105 CE", event: "paper invented in china by cai lun" },
      { year: "313 CE", event: "edict of milan legalizes christianity in the roman empire" },
      { year: "476 CE", event: "fall of the western roman empire" }
    ]
  },
  {
    name: "medieval period",
    dates: "500 - 1400",
    events: [
      { year: "527", event: "justinian i becomes byzantine emperor; reconquests begin" },
      { year: "570", event: "birth of prophet muhammad" },
      { year: "622", event: "muhammad's migration to medina (hijra); start of islamic calendar" },
      { year: "800", event: "charlemagne crowned holy roman emperor" },
      { year: "1066", event: "norman conquest of england (battle of hastings)" },
      { year: "1096", event: "first crusade begins" },
      { year: "1215", event: "magna carta signed in england" },
      { year: "1271", event: "marco polo begins journey to china" },
      { year: "1337", event: "hundred years' war begins between england and france" },
      { year: "1347", event: "black death arrives in europe, killing roughly one-third of the population" },
      { year: "1368", event: "ming dynasty established in china" },
      { year: "1398", event: "timur (tamerlane) sacks delhi" }
    ]
  },
  {
    name: "renaissance",
    dates: "1400 - 1600",
    events: [
      { year: "1439", event: "gutenberg develops the movable-type printing press" },
      { year: "1453", event: "fall of constantinople; end of the byzantine empire" },
      { year: "1469", event: "lorenzo de' medici rises to power in florence" },
      { year: "1486", event: "botticelli paints the birth of venus" },
      { year: "1492", event: "columbus reaches the americas; reconquista completed in spain" },
      { year: "1498", event: "vasco da gama reaches india by sea" },
      { year: "1503", event: "leonardo da vinci begins painting the mona lisa" },
      { year: "1508", event: "michelangelo begins painting the sistine chapel ceiling" },
      { year: "1517", event: "martin luther posts 95 theses; protestant reformation begins" },
      { year: "1543", event: "copernicus publishes heliocentric model; vesalius publishes anatomy" },
      { year: "1558", event: "elizabeth i becomes queen of england" },
      { year: "1599", event: "shakespeare's globe theatre opens in london" }
    ]
  },
  {
    name: "age of exploration",
    dates: "1400 - 1700",
    events: [
      { year: "1405", event: "zheng he begins voyages from china across the indian ocean" },
      { year: "1492", event: "columbus crosses the atlantic and reaches the caribbean" },
      { year: "1498", event: "vasco da gama sails around africa to reach india" },
      { year: "1519", event: "magellan's expedition begins the first circumnavigation of the globe" },
      { year: "1521", event: "hernan cortes conquers the aztec empire" },
      { year: "1533", event: "francisco pizarro conquers the inca empire" },
      { year: "1588", event: "defeat of the spanish armada by england" },
      { year: "1607", event: "jamestown colony founded in virginia" },
      { year: "1620", event: "pilgrims arrive on the mayflower; plymouth colony established" },
      { year: "1642", event: "abel tasman is the first european to reach new zealand" },
      { year: "1648", event: "peace of westphalia; modern nation-state system established" },
      { year: "1652", event: "dutch establish cape colony in south africa" }
    ]
  },
  {
    name: "enlightenment",
    dates: "1685 - 1815",
    events: [
      { year: "1687", event: "newton publishes principia mathematica" },
      { year: "1689", event: "john locke publishes two treatises of government" },
      { year: "1748", event: "montesquieu publishes the spirit of the laws" },
      { year: "1751", event: "diderot and d'alembert begin publishing the encyclopedie" },
      { year: "1762", event: "rousseau publishes the social contract" },
      { year: "1776", event: "american declaration of independence; adam smith publishes wealth of nations" },
      { year: "1781", event: "kant publishes critique of pure reason" },
      { year: "1787", event: "u.s. constitution drafted at the constitutional convention" },
      { year: "1789", event: "french revolution begins; storming of the bastille" },
      { year: "1791", event: "bill of rights ratified in the united states" },
      { year: "1804", event: "napoleon crowned emperor of france; haiti declares independence" },
      { year: "1815", event: "battle of waterloo; congress of vienna redraws european borders" }
    ]
  },
  {
    name: "industrial revolution",
    dates: "1760 - 1900",
    events: [
      { year: "1760", event: "beginning of the industrial revolution in britain" },
      { year: "1769", event: "james watt patents improved steam engine" },
      { year: "1793", event: "eli whitney invents the cotton gin" },
      { year: "1804", event: "first steam locomotive runs in wales" },
      { year: "1831", event: "michael faraday discovers electromagnetic induction" },
      { year: "1837", event: "morse demonstrates the electric telegraph" },
      { year: "1848", event: "revolutions sweep across europe; communist manifesto published" },
      { year: "1859", event: "darwin publishes on the origin of species" },
      { year: "1869", event: "suez canal opens; transcontinental railroad completed in the u.s." },
      { year: "1876", event: "alexander graham bell patents the telephone" },
      { year: "1879", event: "thomas edison develops practical incandescent light bulb" },
      { year: "1895", event: "marconi demonstrates wireless telegraphy; rontgen discovers x-rays" }
    ]
  },
  {
    name: "world wars",
    dates: "1914 - 1945",
    events: [
      { year: "1914", event: "world war i begins after assassination of archduke franz ferdinand" },
      { year: "1915", event: "gallipoli campaign; first large-scale use of chemical weapons" },
      { year: "1917", event: "russian revolution; bolsheviks seize power; u.s. enters wwi" },
      { year: "1918", event: "world war i ends; spanish flu pandemic begins" },
      { year: "1919", event: "treaty of versailles signed; league of nations established" },
      { year: "1929", event: "stock market crash; great depression begins" },
      { year: "1933", event: "hitler becomes chancellor of germany" },
      { year: "1939", event: "world war ii begins with german invasion of poland" },
      { year: "1941", event: "attack on pearl harbor; u.s. enters wwii; germany invades the ussr" },
      { year: "1944", event: "d-day; allied invasion of normandy" },
      { year: "1945", event: "atomic bombs dropped on hiroshima and nagasaki; wwii ends; united nations founded" }
    ]
  },
  {
    name: "modern era",
    dates: "1945 - present",
    events: [
      { year: "1947", event: "india and pakistan gain independence; cold war begins" },
      { year: "1948", event: "state of israel established; universal declaration of human rights adopted" },
      { year: "1949", event: "people's republic of china established under mao zedong; nato formed" },
      { year: "1957", event: "sputnik launched; space age begins" },
      { year: "1961", event: "berlin wall constructed; yuri gagarin becomes first human in space" },
      { year: "1963", event: "march on washington; president kennedy assassinated" },
      { year: "1969", event: "first moon landing (apollo 11)" },
      { year: "1989", event: "fall of the berlin wall; tiananmen square protests" },
      { year: "1991", event: "dissolution of the soviet union; world wide web goes public" },
      { year: "2001", event: "september 11 attacks in the united states" },
      { year: "2008", event: "global financial crisis; barack obama elected u.s. president" },
      { year: "2020", event: "covid-19 pandemic spreads worldwide" }
    ]
  }
];

const SHRIMP_QUOTES = [
  "shrimp-based learning is the future",
  "the krill council approves",
  "every great mind started as a small shrimp",
  "you're doing shrimpendously well today",
  "the ocean of knowledge awaits, little krill",
  "stay curious, stay shrimpy",
  "a shrimp a day keeps the ignorance away",
  "shell yeah, you got it right",
  "in the sea of academics, be a mantis shrimp — see more than others",
  "the krill academy believes in you, even on your worst tide",
  "plankton-sized steps lead to whale-sized results",
  "don't be shellfish with your knowledge — share it",
  "homework is just brain food for growing shrimp",
  "even the tiniest krill can make waves",
  "studying is just marinating your brain",
  "when in doubt, shrimp it out",
  "the prawn of a new day brings new lessons",
  "may your grades be as high as the tide",
  "you're one in a krillion",
  "school of fish? more like school of brilliance",
  "let your curiosity be as deep as the mariana trench",
  "shrimply the best study session yet",
  "the coral of wisdom grows slowly but beautifully",
  "keep swimming — even shrimp move forward",
  "reef-reshingly good progress today",
  "your brain is more powerful than an electric eel",
  "a wise shrimp once said: read the textbook",
  "don't let anyone tell you you're too small to learn big things",
  "the krill curriculum is approved by neptune himself",
  "tide and error is how we learn",
  "you've got the world on a half shell",
  "seas the day and study hard",
  "that answer was absolutely jaw-fish dropping",
  "remember: even the ocean started as tiny drops",
  "shrimp cocktail of knowledge: facts, formulas, and fun",
  "you're krilling it right now",
  "the deep sea of calculus fears no shrimp",
  "be like water — adaptable, persistent, and full of shrimp",
  "another day, another chance to be shrimpressive",
  "the krill academy salutes your dedication to learning"
];

const UNITS = {
  length: {
    meter: 1,
    kilometer: 1000,
    centimeter: 0.01,
    millimeter: 0.001,
    micrometer: 0.000001,
    mile: 1609.344,
    yard: 0.9144,
    foot: 0.3048,
    inch: 0.0254
  },
  weight: {
    kilogram: 1,
    gram: 0.001,
    milligram: 0.000001,
    pound: 0.453592,
    ounce: 0.0283495,
    "ton (us)": 907.185,
    "metric ton": 1000
  },
  temperature: {
    units: ["celsius", "fahrenheit", "kelvin"],
    toBase: {
      celsius: function (v) { return v; },
      fahrenheit: function (v) { return (v - 32) * 5 / 9; },
      kelvin: function (v) { return v - 273.15; }
    },
    fromBase: {
      celsius: function (v) { return v; },
      fahrenheit: function (v) { return v * 9 / 5 + 32; },
      kelvin: function (v) { return v + 273.15; }
    }
  },
  volume: {
    liter: 1,
    milliliter: 0.001,
    gallon: 3.78541,
    quart: 0.946353,
    pint: 0.473176,
    cup: 0.236588,
    "fluid ounce": 0.0295735,
    "cubic meter": 1000
  },
  speed: {
    "m/s": 1,
    "km/h": 0.277778,
    "mph": 0.44704,
    "knot": 0.514444,
    "ft/s": 0.3048
  },
  time: {
    second: 1,
    millisecond: 0.001,
    minute: 60,
    hour: 3600,
    day: 86400,
    week: 604800,
    year: 31557600
  },
  area: {
    "square meter": 1,
    "square kilometer": 1000000,
    "square centimeter": 0.0001,
    "square mile": 2589988.11,
    "square yard": 0.836127,
    "square foot": 0.092903,
    "acre": 4046.86,
    "hectare": 10000
  }
};
